// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFSYfoSkRId5WU8z7Az8s_2IRQ-ZA4ytA',
    appId: '1:621359063442:web:78f37363e69e9c2daf614b',
    messagingSenderId: '621359063442',
    projectId: 'grocery-app-b0cbb',
    authDomain: 'grocery-app-b0cbb.firebaseapp.com',
    storageBucket: 'grocery-app-b0cbb.appspot.com',
    measurementId: 'G-ZLMYVJB0KQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfmVJHob5vtpCOG-1sTuRIGaFWXuwGvkE',
    appId: '1:621359063442:android:ed90e93234db990baf614b',
    messagingSenderId: '621359063442',
    projectId: 'grocery-app-b0cbb',
    storageBucket: 'grocery-app-b0cbb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDD18DZizSbpUwAtRjHC0ErLkrVuXQvxRo',
    appId: '1:621359063442:ios:d2be474a5dd920d3af614b',
    messagingSenderId: '621359063442',
    projectId: 'grocery-app-b0cbb',
    storageBucket: 'grocery-app-b0cbb.appspot.com',
    iosClientId: '621359063442-eucsjm461dohg026s2111edtm47sbvco.apps.googleusercontent.com',
    iosBundleId: 'com.example.adminPanelGroceryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDD18DZizSbpUwAtRjHC0ErLkrVuXQvxRo',
    appId: '1:621359063442:ios:d2be474a5dd920d3af614b',
    messagingSenderId: '621359063442',
    projectId: 'grocery-app-b0cbb',
    storageBucket: 'grocery-app-b0cbb.appspot.com',
    iosClientId: '621359063442-eucsjm461dohg026s2111edtm47sbvco.apps.googleusercontent.com',
    iosBundleId: 'com.example.adminPanelGroceryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFSYfoSkRId5WU8z7Az8s_2IRQ-ZA4ytA',
    appId: '1:621359063442:web:78150d0a7f137873af614b',
    messagingSenderId: '621359063442',
    projectId: 'grocery-app-b0cbb',
    authDomain: 'grocery-app-b0cbb.firebaseapp.com',
    storageBucket: 'grocery-app-b0cbb.appspot.com',
    measurementId: 'G-K8ZGTD9S5P',
  );
}
